# Dry Run Configuration for Ubuntu Environment
# Minimal resource usage for quick pipeline testing

# Model Architecture (Minimal for dry run)
model:
  d_model: 128                    # Reduced from 768 for faster testing
  n_layer: 2                      # Reduced from 12 for faster testing  
  vocab_size: 1000                # Reduced from 50257 for faster testing
  d_state: 8                      # Reduced from 16 for faster testing
  d_conv: 2                       # Reduced from 4 for faster testing
  expand: 2                       # Keep same
  bias: false
  conv_bias: true

# Training Configuration (Minimal steps)
training:
  pretrain:
    optimizer: "AdamW"
    learning_rate: 2e-4
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.98
    eps: 1e-6
    micro_batch_size: 2           # Very small batch for dry run
    max_epochs: 1                 # Only 1 epoch for dry run
    max_steps: 10                 # Only 10 steps for dry run
    log_interval: 2               # Log every 2 steps
    save_interval: 5              # Save every 5 steps
    max_grad_norm: 1.0
    
  finetune:
    optimizer: "AdamW"
    learning_rate: 1e-4
    weight_decay: 0.01
    micro_batch_size: 2           # Very small batch for dry run
    epochs:
      sst2: 1                     # Only 1 epoch for dry run
      mrpc: 1
      qnli: 1
      mnli: 1

# SDM Configuration (Minimal)
sdm:
  lambda_sparsity: 0.01
  gumbel_temp_start: 5.0
  gumbel_temp_end: 0.1
  target_sparsity: 0.3

# SGH-PEFT Configuration (Minimal)
sgh_peft:
  lora_high_rank: 4               # Reduced from 16
  lora_low_rank: 2                # Reduced from 4
  lora_alpha_factor: 2
  lora_dropout: 0.05
  apply_sparsity_mask: true
  freeze_base_model: true

# System Configuration
system:
  device: "cpu"                   # Default to CPU for dry run
  seed: 42
  deterministic: true
  mixed_precision: "bf16"

# Data Configuration (Minimal)
data:
  max_length: 128                 # Reduced from 1024 for faster processing

# Logging Configuration
logging:
  use_wandb: false                # Disable W&B for dry run
  wandb_project: "dry-run-test"

# Path Configuration
paths:
  output_dir: "./dry_run_experiments"

# Experimental Setup (Minimal)
experiments:
  glue_tasks: ["sst2"]            # Only test one task

# Dry Run Specific Settings
dry_run:
  enabled: true
  max_samples: 10                 # Only process 10 samples
  skip_heavy_computation: true
  mock_gpu_operations: true
  quick_validation: true 