# Hyperparameters for M_base and M_SDM (Phase A)
model:
  d_model: 768
  n_layer: 12
  vocab_size: 50257
  d_state: 16
  d_conv: 4
  expand: 2

training:
  batch_size: 32
  learning_rate: 1e-4
  weight_decay: 0.1
  warmup_steps: 1000
  max_steps: 100000
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0

data:
  dataset_name: "wikitext-103-raw-v1"
  max_length: 1024
  num_workers: 4

logging:
  log_interval: 100
  eval_interval: 1000
  save_interval: 5000
  wandb_project: "hardware-data-parameter-codesign"
  run_name: "baseline_ssm"

# SDM-specific parameters (for Phase A structured masking)
sdm:
  sparsity_ratio: 0.5
  masking_schedule: "cosine"
  importance_threshold: 1e-3 