# Hyperparameters for M_base and M_SDM (Phase A)
model:
  d_model: 768
  n_layer: 12
  vocab_size: 50257
  d_state: 16
  d_conv: 4
  expand: 2

training:
  pretrain:
    batch_size: 128
    micro_batch_size: 8
    learning_rate: 2e-4
    weight_decay: 0.1
    warmup_steps_ratio: 0.1
    max_epochs: 20
    max_grad_norm: 1.0

data:
  max_length: 1024
  num_workers: 4

logging:
  log_interval: 100
  eval_interval: 1000
  save_interval: 5000
  wandb_project: "hardware-data-parameter-codesign"
  run_name: "baseline_ssm"

# SDM-specific parameters (for Phase A structured masking)
sdm:
  lambda_sparsity: 0.01
  initial_temperature: 5.0
  final_temperature: 0.1
  target_sparsity: 0.5 